### ISSUE TITLE
The project contains error 

### ISSUE THREAD

**Issue by PedroNunes11** [edvart-ros/unity_asv_sim#22]
The project is showing a compilation error when I try to open it in Unity. Do you know how to fix it?

**Comment by PedroNunes11** [comment]
Assets/Scripts/Physics/Water/Statics/FloatersBurst.cs(72,19): error CS1061: 'WaterSimulationSearchJob' does not contain a definition for 'targetPositionWSBuffer' and no accessible extension method 'targetPositionWSBuffer' accepting a first argument of type 'WaterSimulationSearchJob' could be found (are you missing a using directive or an assembly reference?)

How to fix this?

**Comment by luis-robotic** [comment]
Which version are you using? I am having the same problem on 2022.3.37f1

**Comment by edvart-ros** [comment]
Hmm. That definitely sounds like a Unity version thing. The water system is still new and they change the API a lot. 

I'm not able to maintain this project anymore, but I would have a look at the "scripting in the HDRP water system" page : https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@14.0/manual/WaterSystem-scripting.html for the version you're using. Most likely, it's a matter of changing some function names and arguments.

**Comment by edvart-ros** [comment]
I just tested a fresh clone in 2023.2.20f1, and everything works okay (with a new commit that fixes another stupid versioning bug. Sorry about that).

As for other versions, you'll have to look up the documentation of the HDRP water system to see how the API is defined.
