### ISSUE TITLE
Ship is not moving with the wave even though the wind and wave are high

### ISSUE THREAD

**Issue by adarsha-s-bharadwaj** [edvart-ros/unity_asv_sim#25]
Hi I'm currently learning about the behavior of the ships in certain environments. So I was working with your project. These are the problems which i'm facing right now.
1. I have a error showing a mesh missing in simplified Mesh in submersion script of seperate_parts.
2. The ship is not moving with the waves even though I changed the settings of winds and waves, the ship still stands there only behaving with waves but does not change the position. Maybe the hydrodynamics for the wam-v ship is not included or not working. Please help me with this. 
3. I am trying to visualise the lidar and camera of the wam-v boat itself in rviz and I don't know how to proceed with the wam-v boat itself for ros2 humble. Can you please tell me how to visualise the sensors of the wam-v ship from unity to rviz2.

![Screenshot from 2024-08-01 12-31-13](https://github.com/user-attachments/assets/be008839-b163-4f02-a045-f9a7daff204e)
![Screenshot from 2024-08-01 12-32-56](https://github.com/user-attachments/assets/90279482-0d84-4a7f-a9ab-c913361e507e)

**Comment by edvartGB** [comment]
1. The simplified mesh (used for submersion calculation) has not been set, in your screenshot. Without this, buoyancy cannot be calculated.
2. Ocean current not implemented.
3. Look at the ros transform system. You need an URDF with correct frame ids to visualize the sensor data. theres some help in the wiki, but u might need to learn more about urdf, tf, and ros.
